apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tor
  name: tor-frontend-deploy
spec:
  replicas: 1
  selector:
       matchLabels:
            app: tor-frontend
  template:
      metadata:
        labels:
           app: tor-frontend
      spec:
         hostAliases:
         - ip: "15.165.36.43"
           hostnames:
           - "www.tor-kurly.com"
         containers:
         - name: tor-frontend
           image: #VERSION_STRING#
           ports:
           - name: frontend-port
             containerPort: 3000
           imagePullPolicy: IfNotPresent
           resources:
             limits:
               cpu: "2000m"
               memory: "2048Mi"
             requests:
               cpu: "2000m"
               memory: "2048Mi"
         volumes:
         - name: tz-seoul
           hostPath:
              path: /usr/share/zoneinfo/Asia/Seoul
