apiVersion: v1
kind: Service
metadata:
   name: tor-frontend-svc
   namespace: tor
   labels:
      app: tor-frontend
spec:
   type: NodePort
   ports:
   - name: frontend-port
     port: 3000
     targetPort: 3000
     nodePort: 30300
   selector:
       app: tor-frontend
